profile: dev

spring:
  application:
    name: config-dev
    
config:
  info: master-branch, config-dev.yml version=0.0.1SnapShot
  
database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cloudlearning?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: root